add_newline = false
command_timeout = 1000
format = "[î‚¶](surface1)[${battery}](fg:white bg:surface1)${os}[î‚´](bg:surface2 fg:surface1)$sudo$username[î‚´](bg:overlay0 fg:surface2)$hostname[î‚´](bg:mauve fg:overlay0)[$c$dart$dotnet$elixir$elm$erlang$golang$haskell$haxe$java$julia$kotlin$lua$nim$bun$nodejs$rlang$ruby$rust$perl$php$python$scala$swift$zig$package$git_branch](fg:base bg:mauve)[î‚´](fg:mauve bg:peach)[${git_state}${git_status}](fg:base bg:peach)[î‚´](fg:peach bg:yellow)[$container$direnv$nix_shell$cmd_duration$jobs$shlvl$status](fg:base bg:yellow)$character"
right_format = "[î‚¶](fg:blue)[$directory](fg:base bg:blue)"
palette = "catppuccin_mocha"

[battery]
format = "$symbol"

[[battery.display]]
threshold = 100

[c]
format = "$symbol"
symbol = "î˜"

[character]
disabled = false
error_symbol = "(fg:red bg:pink)[î‚´](fg:pink) "
format = "$symbol"
success_symbol = "[î‚´](fg:teal) "

[cmd_duration]
format = " ï”  $duration"
min_time = 2500
min_time_to_notify = 60000
show_notifications = false

[container]
format = " $symbol $name"
symbol = "ó±‹©"

[dart]
format = "$symbol"
symbol = "î™Œ"

[directory]
fish_style_pwd_dir_length = 1
read_only = " ó°ˆˆ"
read_only_style = "fg:red bg:blue"
repo_root_style = "$style"
before_repo_root_style = "fg:dimmed bg:blue"
style = "fg:base bg:blue"
truncation_length = 3

[direnv]
allowed_msg = ""
denied_msg = ""
disabled = false
format = " $loaded"
loaded_msg = "ó°"
not_allowed_msg = ""
symbol = ""
unloaded_msg = "ó°™§"

[dotnet]
format = "$symbol"
symbol = "î™ˆ"

[elixir]
format = "$symbol"
symbol = "î˜­"

[elm]
format = "$symbol"
symbol = "î˜¬"

[erlang]
format = "$symbol"
symbol = "ïˆ¿"

[git_branch]
format = " $symbol $branch"
symbol = "îœ¥"

[git_state]
disabled = false
format = "$state (${progress_current}/${progress_total}) "

[git_status]
format = " $all_status$ahead_behind"
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
up_to_date = "âœ”ï¸"

[golang]
format = "$symbol"
symbol = "î˜§"

[haskell]
format = "$symbol"
symbol = "ó°²’"

[haxe]
format = "$symbol"
symbol = "î™¦"

[hostname]
disabled = false
format = "[$hostname]($style)[$ssh_symbol](fg:maroon)"
ssh_only = false
ssh_symbol = " ó°–ˆ"
style = "fg:red"

[java]
format = "$symbol"
symbol = "ó°¬·"

[jobs]
format = " $symbol $number"
symbol = "ó°£–"

[julia]
format = "$symbol"
symbol = "î˜¤"

[kotlin]
format = "$symbol"
symbol = "î˜´"

[lua]
format = "$symbol"
symbol = "î˜ "

[nim]
format = "$symbol"
symbol = "î™·"

[nix_shell]
format = "$symbol"
symbol = "ó±„…"

[bun]
format = "$symbol"
detect_files = ['.bun-versoin', 'bun.toml', 'bun.lock', 'bun.lockb']
symbol = "ğŸ¥Ÿ"

[nodejs]
format = "$symbol"
detect_files = [
  'package.json',
  '.node-version',
  '!bunfig.toml',
  '!bun.lockb',
  '!bun.lock',
]
symbol = "ï‹¯"

[os]
format = "$symbol[ ](bg:surface1)"
disabled = false

[os.symbols]
AlmaLinux = "[ïŒ](fg:text bg:surface1)"
Alpine = "[ïŒ€](fg:blue bg:surface1)"
Amazon = "[ï‰°](fg:peach bg:surface1)"
Android = "[îœ](fg:green bg:surface1)"
Arch = "[ó°£‡](fg:sapphire bg:surface1)"
Artix = "[ïŒŸ](fg:sapphire bg:surface1)"
CentOS = "[ïŒ„](fg:mauve bg:surface1)"
Debian = "[ïŒ†](fg:red bg:surface1)"
DragonFly = "[î»¸](fg:teal bg:surface1)"
EndeavourOS = "[ïŒ¢](fg:mauve bg:surface1)"
Fedora = "[ïŒŠ](fg:blue bg:surface1)"
FreeBSD = "[ïŒŒ](fg:red bg:surface1)"
Garuda = "[ïŒ·](fg:sapphire bg:surface1)"
Gentoo = "[ïŒ](fg:lavender bg:surface1)"
Illumos = "[ïŒ¦](fg:peach bg:surface1)"
Kali = "[ïŒ§](fg:blue bg:surface1)"
Linux = "[ïŒš](fg:yellow bg:surface1)"
Macos = "[ïŒ‚](fg:text bg:surface1)"
Manjaro = "[ïŒ’](fg:green bg:surface1)"
Mint = "[ó°£­](fg:teal bg:surface1)"
NixOS = "[ïŒ“](fg:sky bg:surface1)"
OpenBSD = "[ïŒ¨](fg:yellow bg:surface1)"
Pop = "[ïŒª](fg:sapphire bg:surface1)"
Raspbian = "[ïŒ•](fg:maroon bg:surface1)"
RedHatEnterprise = "[î½](fg:red bg:surface1)"
Redhat = "[î½](fg:red bg:surface1)"
RockyLinux = "[ïŒ«](fg:green bg:surface1)"
SUSE = "[ïŒ”](fg:green bg:surface1)"
Solus = "[ïŒ­](fg:blue bg:surface1)"
Ubuntu = "[î¯‰](fg:peach bg:surface1)"
Unknown = "[ï™](fg:text bg:surface1)"
Void = "[ïŒ®](fg:green bg:surface1)"
Windows = "[ó°–³](fg:sky bg:surface1)"
openSUSE = "[ïŒ”](fg:green bg:surface1)"

[package]
format = " $version"
version_format = "$raw"

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[perl]
format = "$symbol"
symbol = "î™¾"

[php]
format = "$symbol"
symbol = "ó°ŒŸ"

[python]
format = "$symbol"
symbol = "î´›"

[rlang]
format = "$symbol"
symbol = "î·"

[ruby]
format = "$symbol"
symbol = "îœ¹"

[rust]
format = "$symbol"
symbol = "î¨"

[scala]
format = "$symbol"
symbol = "îš"

[shlvl]
disabled = false
format = "[ $symbol]($style)"
repeat = false
style = "fg:surface1 bg:yellow"
symbol = "ó±†ƒ"
threshold = 3

[status]
disabled = false
format = "$symbol"
map_symbol = true
not_executable_symbol = "[î‚´](fg:yellow bg:pink)[ î¯ $common_meaning](fg:red bg:pink)"
not_found_symbol = "[î‚´](fg:yellow bg:pink)[ ó°©Œ $common_meaning](fg:red bg:pink)"
sigint_symbol = "[î‚´](fg:yellow bg:pink)[ ï‰– $signal_name](fg:red bg:pink)"
signal_symbol = "[î‚´](fg:yellow bg:pink)[ âš¡ $signal_name](fg:red bg:pink)"
style = ""
success_symbol = "[î‚´](fg:yellow bg:teal)"
symbol = "[î‚´](fg:yellow bg:pink)[ ï¡ $status](fg:red bg:pink)"

[sudo]
disabled = false
format = "[ $symbol]($style)"
style = "fg:rosewater bg:surface2"
symbol = "ó°Œ‹"

[swift]
format = "$symbol"
symbol = "îš™"

[time]
disabled = true

[username]
format = "[$user]($style)"
show_always = true
style_root = "fg:red bg:surface2"
style_user = "fg:green bg:surface2"
[username.aliases]
#laney = "ó°´"
root = "ó°±¯"

[zig]
format = "$symbol"
symbol = "îš©"
